version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  server:
    build:
      context: ./apps/server
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file: .env
    volumes:
      - ./apps/server:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "start:dev"]
    depends_on:
      - postgres

  ui:
    build:
      context: ./apps/ui
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file: .env
    volumes:
      - ./apps/ui:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    # command: ["serve", "-s", "dist", "-l", "${FRONTEND_PORT}"]
    depends_on:
      - server
